-- Harness 控制平面表（MySQL 8）。
-- 开发环境可由 JPA ddl-auto 辅助；生产环境应显式执行本脚本。
-- 参见 docs/design-docs/ADR-001-harness-boundaries.md

CREATE TABLE IF NOT EXISTS harness_run (
    run_id CHAR(36) NOT NULL COMMENT '运行UUID',
    definition_id VARCHAR(64) NOT NULL COMMENT 'Harness定义ID',
    definition_version INT NOT NULL COMMENT '定义版本号',
    definition_hash CHAR(64) NOT NULL COMMENT '定义内容SHA-256',
    run_type VARCHAR(32) NOT NULL COMMENT 'AGENT_LOOP或DETERMINISTIC_WORKFLOW',
    status VARCHAR(24) NOT NULL COMMENT 'CREATED/QUEUED/RUNNING/WAITING_APPROVAL/VERIFYING/SUCCEEDED/FAILED/CANCELLED/TIMED_OUT',
    objective TEXT NULL COMMENT '用户目标摘要',
    conversation_id CHAR(36) NULL COMMENT '会话ID（预留）',
    requester_id VARCHAR(64) NULL COMMENT '请求者ID（预留）',
    client_request_id VARCHAR(128) NULL COMMENT '客户端幂等键',
    transaction_log_id BIGINT NULL COMMENT '关联现有对话日志（可选）',
    trace_id VARCHAR(64) NULL COMMENT '全链路追踪ID',
    current_step INT NOT NULL DEFAULT 0 COMMENT '当前步骤序号',
    max_steps INT NOT NULL DEFAULT 8 COMMENT '最大步骤数',
    model_call_count INT NOT NULL DEFAULT 0 COMMENT '已发生模型调用次数',
    tool_call_count INT NOT NULL DEFAULT 0 COMMENT '已发生工具调用次数',
    input_tokens INT NOT NULL DEFAULT 0 COMMENT '累计输入Token',
    output_tokens INT NOT NULL DEFAULT 0 COMMENT '累计输出Token',
    cancel_requested TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否请求取消',
    lease_owner VARCHAR(128) NULL COMMENT '当前Worker标识',
    lease_token CHAR(36) NULL COMMENT '不可复用租约令牌',
    lease_expires_at DATETIME(6) NULL COMMENT '租约过期时间',
    final_output_preview VARCHAR(2000) NULL COMMENT '最终输出脱敏摘要',
    final_artifact_id CHAR(36) NULL COMMENT '最终报告Artifact',
    error_code VARCHAR(64) NULL COMMENT '失败错误码',
    error_message TEXT NULL COMMENT '失败信息',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    created_at DATETIME(6) NOT NULL COMMENT '创建时间',
    started_at DATETIME(6) NULL COMMENT '开始执行时间',
    finished_at DATETIME(6) NULL COMMENT '结束时间',
    updated_at DATETIME(6) NOT NULL COMMENT '更新时间',
    PRIMARY KEY (run_id),
    UNIQUE KEY uq_harness_run_client_request (client_request_id),
    KEY idx_harness_run_status_created (status, created_at),
    KEY idx_harness_run_definition (definition_id, definition_version),
    KEY idx_harness_run_trace (trace_id),
    KEY idx_harness_run_lease (status, lease_expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Harness运行主表';

CREATE TABLE IF NOT EXISTS harness_step (
    step_id CHAR(36) NOT NULL COMMENT '步骤UUID',
    run_id CHAR(36) NOT NULL COMMENT '所属运行ID',
    sequence_no INT NOT NULL COMMENT '步骤序号',
    step_type VARCHAR(32) NOT NULL COMMENT 'INTAKE/CONTEXT_BUILD/MODEL_DECISION/...',
    status VARCHAR(24) NOT NULL COMMENT 'PENDING/RUNNING/SUCCEEDED/FAILED/SKIPPED',
    attempt INT NOT NULL DEFAULT 1 COMMENT '尝试次数',
    decision_summary VARCHAR(2000) NULL COMMENT '决策摘要（非思维链）',
    input_hash CHAR(64) NULL COMMENT '输入内容哈希',
    output_hash CHAR(64) NULL COMMENT '输出内容哈希',
    model_provider VARCHAR(32) NULL COMMENT '模型提供商',
    model_name VARCHAR(128) NULL COMMENT '模型名称',
    input_tokens INT NULL COMMENT '本步输入Token',
    output_tokens INT NULL COMMENT '本步输出Token',
    duration_ms BIGINT NULL COMMENT '耗时毫秒',
    error_code VARCHAR(64) NULL COMMENT '错误码',
    error_message TEXT NULL COMMENT '错误信息',
    started_at DATETIME(6) NULL COMMENT '开始时间',
    finished_at DATETIME(6) NULL COMMENT '结束时间',
    PRIMARY KEY (step_id),
    UNIQUE KEY uq_harness_step_run_seq (run_id, sequence_no),
    KEY idx_harness_step_run (run_id),
    CONSTRAINT fk_harness_step_run FOREIGN KEY (run_id) REFERENCES harness_run (run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Harness步骤表';

CREATE TABLE IF NOT EXISTS harness_tool_call (
    tool_call_id CHAR(36) NOT NULL COMMENT '工具调用UUID',
    run_id CHAR(36) NOT NULL COMMENT '所属运行ID',
    step_id CHAR(36) NULL COMMENT '关联步骤ID',
    tool_name VARCHAR(64) NOT NULL COMMENT '工具名称',
    tool_version VARCHAR(16) NOT NULL DEFAULT '1' COMMENT '工具版本',
    risk_level VARCHAR(24) NOT NULL COMMENT 'READ_ONLY/WRITE/DESTRUCTIVE/...',
    status VARCHAR(24) NOT NULL COMMENT 'PENDING/APPROVED/REJECTED/RUNNING/SUCCEEDED/FAILED',
    arguments_redacted_json JSON NULL COMMENT '脱敏后的参数JSON',
    arguments_hash CHAR(64) NOT NULL COMMENT '参数哈希',
    idempotency_key VARCHAR(128) NOT NULL COMMENT '幂等键',
    result_preview VARCHAR(2000) NULL COMMENT '结果脱敏摘要',
    result_artifact_id CHAR(36) NULL COMMENT '完整结果Artifact',
    result_hash CHAR(64) NULL COMMENT '结果哈希',
    duration_ms BIGINT NULL COMMENT '耗时毫秒',
    approval_id CHAR(36) NULL COMMENT '关联审批ID',
    error_code VARCHAR(64) NULL COMMENT '错误码',
    error_message TEXT NULL COMMENT '错误信息',
    created_at DATETIME(6) NOT NULL COMMENT '创建时间',
    finished_at DATETIME(6) NULL COMMENT '完成时间',
    PRIMARY KEY (tool_call_id),
    UNIQUE KEY uq_harness_tool_idempotency (tool_name, idempotency_key),
    KEY idx_harness_tool_run (run_id),
    KEY idx_harness_tool_step (step_id),
    CONSTRAINT fk_harness_tool_run FOREIGN KEY (run_id) REFERENCES harness_run (run_id),
    CONSTRAINT fk_harness_tool_step FOREIGN KEY (step_id) REFERENCES harness_step (step_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Harness工具调用表';

CREATE TABLE IF NOT EXISTS harness_approval (
    approval_id CHAR(36) NOT NULL COMMENT '审批UUID',
    run_id CHAR(36) NOT NULL COMMENT '所属运行ID',
    tool_call_id CHAR(36) NOT NULL COMMENT '关联工具调用',
    status VARCHAR(16) NOT NULL COMMENT 'PENDING/APPROVED/REJECTED/EXPIRED',
    risk_summary VARCHAR(1000) NULL COMMENT '风险说明',
    requested_action VARCHAR(128) NOT NULL COMMENT '请求动作',
    arguments_redacted_json JSON NULL COMMENT '脱敏参数',
    arguments_hash CHAR(64) NOT NULL COMMENT '参数哈希（审批绑定）',
    requested_by VARCHAR(64) NULL COMMENT '请求者',
    decided_by VARCHAR(64) NULL COMMENT '审批人',
    decision_comment VARCHAR(2000) NULL COMMENT '审批意见',
    expires_at DATETIME(6) NOT NULL COMMENT '过期时间',
    decided_at DATETIME(6) NULL COMMENT '决策时间',
    created_at DATETIME(6) NOT NULL COMMENT '创建时间',
    PRIMARY KEY (approval_id),
    KEY idx_harness_approval_run (run_id),
    KEY idx_harness_approval_status (status, expires_at),
    CONSTRAINT fk_harness_approval_run FOREIGN KEY (run_id) REFERENCES harness_run (run_id),
    CONSTRAINT fk_harness_approval_tool FOREIGN KEY (tool_call_id) REFERENCES harness_tool_call (tool_call_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Harness人工审批表';

CREATE TABLE IF NOT EXISTS harness_event (
    event_id CHAR(36) NOT NULL COMMENT '事件UUID',
    run_id CHAR(36) NOT NULL COMMENT '所属运行ID',
    sequence_no INT NOT NULL COMMENT '事件序号',
    event_type VARCHAR(64) NOT NULL COMMENT '事件类型',
    payload_redacted_json JSON NULL COMMENT '脱敏载荷',
    created_at DATETIME(6) NOT NULL COMMENT '创建时间',
    PRIMARY KEY (event_id),
    UNIQUE KEY uq_harness_event_run_seq (run_id, sequence_no),
    KEY idx_harness_event_run (run_id),
    CONSTRAINT fk_harness_event_run FOREIGN KEY (run_id) REFERENCES harness_run (run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Harness事件流（SSE/时间线）';

CREATE TABLE IF NOT EXISTS harness_artifact (
    artifact_id CHAR(36) NOT NULL COMMENT 'Artifact UUID',
    run_id CHAR(36) NOT NULL COMMENT '所属运行ID',
    step_id CHAR(36) NULL COMMENT '关联步骤',
    artifact_type VARCHAR(64) NOT NULL COMMENT '类型',
    bucket VARCHAR(128) NULL COMMENT 'MinIO bucket',
    object_path VARCHAR(1024) NULL COMMENT 'MinIO对象路径',
    content_type VARCHAR(128) NULL COMMENT 'MIME类型',
    size_bytes BIGINT NULL COMMENT '字节大小',
    sha256 CHAR(64) NULL COMMENT '内容哈希',
    retention_until DATETIME(6) NULL COMMENT '保留截止时间',
    created_at DATETIME(6) NOT NULL COMMENT '创建时间',
    PRIMARY KEY (artifact_id),
    KEY idx_harness_artifact_run (run_id),
    CONSTRAINT fk_harness_artifact_run FOREIGN KEY (run_id) REFERENCES harness_run (run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Harness大型产物元数据';
