CREATE TABLE IF NOT EXISTS document_upload_task (
    task_id VARCHAR(36) NOT NULL PRIMARY KEY COMMENT '任务UUID',
    file_id VARCHAR(64) NULL COMMENT '生成的向量文件ID',
    file_name VARCHAR(512) NOT NULL COMMENT '原始文件名',
    temp_file_path VARCHAR(1024) NOT NULL COMMENT '临时文件路径',
    content_type VARCHAR(128) NULL COMMENT '上传Content-Type',
    file_size_bytes BIGINT NOT NULL COMMENT '文件大小字节',
    chunk_strategy VARCHAR(24) NOT NULL COMMENT '分块策略',
    parse_mode VARCHAR(16) NOT NULL COMMENT '解析模式',
    status VARCHAR(16) NOT NULL COMMENT '任务状态',
    phase VARCHAR(24) NOT NULL COMMENT '当前阶段',
    percent INT NOT NULL DEFAULT 0 COMMENT '整体进度0-100',
    message VARCHAR(512) NULL COMMENT '进度说明',
    eta_seconds BIGINT NULL COMMENT '预计剩余秒数',
    docforge_job_id VARCHAR(64) NULL COMMENT 'DocForge异步解析任务ID',
    graph_index_enqueued TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否已入队Neo4j构图',
    result_json TEXT NULL COMMENT '成功结果JSON',
    error_message TEXT NULL COMMENT '失败原因',
    started_at DATETIME(6) NULL COMMENT '开始执行时间',
    finished_at DATETIME(6) NULL COMMENT '结束时间',
    created_at DATETIME(6) NOT NULL COMMENT '创建时间',
    updated_at DATETIME(6) NOT NULL COMMENT '更新时间',
    INDEX idx_upload_task_status_created (status, created_at),
    INDEX idx_upload_task_file_id (file_id)
) COMMENT='文档上传向量化异步任务表';
